template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "5e69b0634aa0bd9773dece52e5b15d3003d605f1"

[replacements]
__GLOTTOLOG_ID__ = "taga1270"
__REPO__ = "lang-tgl"
__UND2C__ = "tl"
__UNDEFINED__ = "Tagalog"
__UND__ = "tgl"
