template = "https://github.com/giellalt/template-lang-und"
rev_id = 104
template_sha = "dbed22967239522b32dd8b46bcf744d91eb00a16"

[replacements]
__REPO__ = "lang-tgl"
__UND2C__ = "tl"
__UNDEFINED__ = "Tagalog"
__UND__ = "tgl"
