template = "https://github.com/giellalt/template-lang-und"
rev_id = 267
template_sha = "eecc8ba78a1297394fa54b425d94002ee6604eb1"

[replacements]
__GLOTTOLOG_ID__ = "taga1270"
__REPO__ = "lang-tgl"
__UND2C__ = "tl"
__UNDEFINED__ = "Tagalog"
__UND__ = "tgl"
